name: documentation
channels:
  - conda-forge
  - defaults
dependencies:
  - babel
  - beautifulsoup4
  - bzip2
  - docutils
  - furo
  - graphviz
  - libgfortran5
  - myst-parser
  - numpy
  - pandas
  - pip
  - python=3.11
  - pytz
  - readline
  - ruamel.yaml
  - setuptools
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx_rtd_theme
  - wheel
