
import os
import subprocess
from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext as _build_ext
import shutil 

class CustomBuildExt(_build_ext):
    def run(self):
        # Run the Makefile to build the Fortran shared object
        subprocess.check_call(['make'])
        # Copy the .so file from build/ to src/seidart/fortran/
        shutil.copy('build/cpmlfdtd.so', 'src/seidart/fortran/')
        # Proceed with the rest of the build process
        super().run()

# Define the Fortran extension that needs to be built
fortran_extension = Extension(
    'seidart.fortran.cpmlfdtd',
    sources=[],  # No source files, since Fortran is built by Make
    libraries=[],  # Any required external libraries
    extra_objects=['src/seidart/fortran/cpmlfdtd.so'],  # The shared library generated by Make
)

setup(
    name='seidart',
    version='2.3.2',
    license='GPL-3.0-or-later',
    author='Steven Bernsen, Christopher Gerbi',
    author_email='steven.bernsen@maine.edu, christopher.gerbi@maine.edu',
    maintainer='Steven Bernsen, Christopher Gerbi',
    maintainer_email='steven.bernsen@maine.edu, christopher.gerbi@maine.edu',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    include_package_data=True,  # Ensures that non-Python files are included
    package_data={
        'seidart': ['fortran/*.so'],  # Include shared libraries in the package
    },
    ext_modules=[fortran_extension],
    cmdclass={'build_ext': CustomBuildExt},
    entry_points={
        'console_scripts': [
            'prjbuild=seidart.routines.prjbuild:main',
            'prjrun=seidart.routines.prjrun:main',
            'arraybuild=seidart.routines.arraybuild:main',
            'sourcefunction=seidart.routines.sourcefunction:main',
            'rcxdisplay=seidart.visualization.rcxdisplay:main',
            'im2anim=seidart.visualization.im2anim:build_animation',
        ],
    },
    install_requires=[
        'numpy',
        'scipy',
        'matplotlib',
        'pandas',
        'mplstereonet',
        'pyevtk',
        'glob2',
        'dill',
        'seaborn'
    ],
    project_urls={
        'Homepage': 'https://github.com/UMainedynamics/SeidarT',
        'Documentation': 'https://umainedynamics.github.io/SeidarT/index.html',
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: GNU Affero General Public License v3',
        'Operating System :: OS Independent',
        'Framework :: Matplotlib',
        'Topic :: Scientific/Engineering :: Physics',
        'Intended Audience :: Science/Research',
        'Natural Language :: English',
        'Development Status :: 4 - Beta'
    ],
    keywords=['wave propagation', 'seismic', 'radar', 'snow', 'ice']
)