name: seidart
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pyevtk
  - python=3.11.8
  - numpy
  - pandas
  - gfortran
  - libgfortran5
  - scipy
  - setuptools
  - seaborn
  - imagemagick
  - ghostscript
  - glob2
  - matplotlib
  - wheel
  - seaborn

  - pip:
      - mplstereonet