name: Build Wheels For MacOS

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install gfortran
        run: brew install gcc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.18.1 numpy

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ENVIRONMENT: |
            FCFLAGS="-arch x86_64 -arch arm64"
            FFLAGS="-arch x86_64 -arch arm64"
            LDFLAGS="-arch x86_64 -arch arm64"

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl

  publish_wheels:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # - name: Install twine
      #   run: python -m pip install twine

      # - name: Publish wheels to PyPI
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: python -m twine upload wheelhouse/*.whl
