name: Build Sphinx Documentation 

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches: 
      - main
      - master
      - develop
      
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: List directories
        run: ls -la /home/runner/work/SeidarT/SeidarT/src/seidart
      
      - name: Install Sphinx and dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install sphinx recommonmark furo
      
      - name: Generate .rst files for specific Python scripts
        run: |
          FOLDERS=('routines' 'visualization' 'simulations')
          for FOLDER in "${FOLDERS[@]}"; do
            MODULE_PATH="/home/runner/work/SeidarT/SeidarT/src/seidart/$FOLDER"
            sphinx-apidoc -o docs/source $MODULE_PATH -e
          done
      
      - name: Copy files to the source directory
        run: |
          cp README.md docs/source 
      
      - name: Build HTML documentation 
        run: |
          cd docs 
          make html 
        
      - name: Commit Documentation Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add docs/ 
          git commit -m "Update documentation" -a || echo "No changes to commit"
          git push
      
  
            
